/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InfoWrap: typeof import('./src/components/shared/InfoWrap.vue')['default']
    MainSponsors: typeof import('./src/components/MainContent/MainSponsors.vue')['default']
    ReviewCard: typeof import('./src/components/shared/ReviewList/ReviewCard.vue')['default']
    ReviewList: typeof import('./src/components/shared/ReviewList/ReviewList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavigation: typeof import('./src/components/TheNavigation.vue')['default']
    VButton: typeof import('./src/components/shared/UI/VButton.vue')['default']
    VInput: typeof import('./src/components/shared/UI/VInput.vue')['default']
  }
}
